### ISSUE TITLE
Consider re-organisation of this repository

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-admin-legacyfilesmigration#1]
To make it easier for those who prefer installing Moodle plugins directly from Git, it is recommended that the Git repository's root folder already holds the plugin's files. In other words, there should not be the folder 'legacyfilesmigration' in this repository but the repository should start with its contents. So the admin can go to their `admin/tool/` folder and run `git clone git@github.com:cperves/moodle-admin-legacyfilesmigration.git legacyfilesmigration` there.

**Comment by cperves** [comment]
Ok

**Comment by cperves** [comment]
Made, Thank U for advices
