### ISSUE TITLE
File local/toolslib.php required

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-admin-legacyfilesmigration#2]
The file `migrateablecoursestable.php` requires file `$CFG->dirroot.'/local/toolslib.php'` that is indeed not part of the plugin. Is that a mistake or forgotten dependency or your local environment?

**Comment by mudrd8mz** [comment]
This leads to fatal error

```
Fatal error: require_once(): Failed opening required '.../local/toolslib.php' in
.../admin/tool/legacyfilesmigration/migrateablecoursestable.php on line 16
```

**Comment by cperves** [comment]
Ouch thank you for erporting that I'm going to correct this

**Comment by cperves** [comment]
I push a new version without that unused reference
