### ISSUE TITLE
No PARAM type specified for hidden form elements

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-admin-legacyfilesmigration#4]
Please make sure to have developer debugging on while developing plugins. I am seeing two messages that may have security related impact:

```
Did you remember to call setType() for 'selectedcourses'? Defaulting to PARAM_RAW cleaning.
Did you remember to call setType() for 'selectedowners'? Defaulting to PARAM_RAW cleaning.
```

You should always set explicit PARAM type for hidden input elements.

**Comment by cperves** [comment]
made
Thanks for this really important fact
