### ISSUE TITLE
Confusing licensing information

### ISSUE THREAD

**Issue by mudrd8mz** [cperves/moodle-admin-legacyfilesmigration#5]
The plugin description and the code itself mentions two licenses:

```
@license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
@license    http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
```

Does it mean you distribute the plugin dual-licensed? Note that all Moodle plugins are considered as derivate work of the Moodle core itself so they should all use plain GPLv3 license to avoid incompatibilities.
I understand from http://www.cecill.info/faq.en.html#gpl that CeCILL is compatible with GPL so it should not be a problem. However, this should be clarified.

**Comment by cperves** [comment]
I saw with our specialist we'll only keep GPL3 since code is written with moodle framework and not from scratch (cecill is not compatible with derivated works)

**Comment by cperves** [comment]
made
